apiVersion: apps/v1
kind: Deployment
metadata:
  name: casbin
  namespace: default
  labels:
    name: casbin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: casbin
  template:
    metadata:
      name: casbin
      labels:
        name: casbin
    spec:
      containers:
        - name: webhook
          image: casbin/k8s_authz:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: authz
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: casbin
  namespace: default
  labels:
    name: casbin
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 8080
  selector:
    name: casbin